### PR TITLE
wip, adding rust

### PR DESCRIPTION
**Pull request by ZuseZ4**

### CODE REVIEW

**Comment by ZuseZ4** [comment]
For the Rust side we have changes to rustc itself, so there is no way to just link Enzyme in.
Shall I thus just change 
`setProperty "compiler.clang$version-enzyme-$branch.exe" "/opt/compiler-explorer/$compiler/bin/clang++" "/tmp/ce/c++.enzyme.properties"` to link to the cargo (rustc?) binary in the /app folder?

**Comment by jedbrown** [comment]
I'd like to get this going and would be able to host the builder for new rust-enzyme images. Are there docs somewhere for what is needed, or someone who can advise assuming I can build a Rust toolchain in whatever environment you like?

**Comment by wsmoses** [comment]
@jedbrown @ZuseZ4 you both now have write permissions to the repo.

Not sure what else is required, would probably be a question for @tgymnich

**Comment by tgymnich** [comment]
For deployment somebody just needs to run [update.sh](https://github.com/EnzymeAD/enzyme-explorer/blob/main/update.sh) on the enzyme-ce machine (just ping me). Also feel free to reach out if I can help in any way.

**Comment by wsmoses** [comment]
If possible, I'd like to reduce the frequency of the rust rebuilds to nightly (rather than the Enzyme rebuild which does much more frequently), to ensure latency of EnzymeCore updates is reasonable.

**Comment by ZuseZ4** [comment]
I don't think it can be reasonably built from scratch on a 4c gh runner, so I think for now it's better if Jed hosts it completely and we just download artifacts here. I feel like once Enzyme can be build against the pre-build LLVM from Rust's official download-CI it would make sense to move it over. 

Also, Enzyme is just a .so here, so I assume it should later be possible to silently delete it and replace it by a newer LLVMEnzyme.so, without rebuilding Rust (assuming no breaking Enzym change).

**Comment by wsmoses** [comment]
Is there anything preventing that right now? Enzyme works on llvm main

**Comment by ZuseZ4** [comment]
Yes, it's the discussion we had here:

**Comment by wsmoses** [comment]
I think you forgot to add a link since I don't see anything after the colon. In any case, if you're referring to the MSVC issue, that only makes it difficulty to build with MSVC in windows. Since the this is built with clang/gcc (and on Linux), it should be fine.

**Comment by ZuseZ4** [comment]
created Rust issue (though it could live in Enzyme core too)
https://github.com/EnzymeAD/rust/issues/79

**Comment by ZuseZ4** [comment]
Given that there is no progress on building Enzyme on Rust's LLVM, lets keep the Rust version fixed.
@jedbrown As you just mentioned in the chat, can you precompile Rust/LLVM/Enzyme, s.t. we can add the artifacts here? On every Enzyme update I would then just delete and replace the old LLVMEnzyme-<X>.so
cc @tgymnich, since I don't know what's the best way to add the precompiled Rust to the image.

**Comment by tgymnich** [comment]
@ZuseZ4 Just download it inside https://github.com/EnzymeAD/enzyme-explorer/blob/main/builder/install-compilers.sh. The binary should run on ubuntu 22.

**Comment by ZuseZ4** [comment]
@jedbrown Shall we give this another try, now that we have a working Rust CI? I assume it should be possible to just pull in the latest artifact from /rust?

**Comment by jedbrown** [comment]
Thanks. It's probably possible to tar up the whole build directory, but I wanted to get `x dist` working because that's clearly the right way to distribute, and necessary for upstreaming.

**Comment by ZuseZ4** [comment]
@tgymnich @wsmoses A rustc dev fixed the dist build for us, so now we have a rust.tar.gz file with 320MB which includes all that we need. We'd just need to download and unpack it. Do you have a good place to where we could upload the tar, since we currently still generate those by hand?

**Comment by tgymnich** [comment]
@ZuseZ4 you could add the rustc tar as a binary artefact to a release.

**Comment by tgymnich** [comment]
closed-ish by 6f73fd0

**Comment by wsmoses** [comment]
hm something is still awry:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0463`.
Compiler returned: 1
```

**Comment by ZuseZ4** [comment]
Yep, but we're aware of it and looking into fixes.

**Pull request closed without merging**
